AllCops:
  TargetRubyVersion: 3.1
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*.gemfile'
    - 'gemfiles/vendor/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - '*.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Max: 20

Style/NumericLiterals:
  Enabled: false