name: RSpec

on:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  rspec:
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3']
        gemfile: ["gemfiles/rails_7_0.gemfile", "gemfiles/rails_7_1.gemfile", "gemfiles/rails_6_1.gemfile"]

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rake spec
